version: '2'
services:
  octo_print:
    build: .
    ports:
    - "5050:5000"
    volumes:
    - ${PWD}:/app
  mjpeg_streamer:
    image: kennethjiang/stub-mjpeg-streamer
    ports:
    - "8080:8080"
